"""move code promo to vendor

Revision ID: 4d0d20525148
Revises: 9db6cc3d3345
Create Date: 2023-11-12 04:05:17.767701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4d0d20525148"
down_revision = "9db6cc3d3345"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_details_id", table_name="product_details")
    op.drop_table("product_details")
    op.drop_column("product", "valid_code_end")
    op.drop_column("product", "valid_code_start")
    op.drop_column("product", "code_promo")
    op.add_column(
        "vendors", sa.Column("code_promo", sa.String(length=256), nullable=True)
    )
    op.add_column("vendors", sa.Column("date_validation", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "date_validation")
    op.drop_column("vendors", "code_promo")
    op.add_column(
        "product", sa.Column("code_promo", mysql.VARCHAR(length=256), nullable=True)
    )
    op.add_column(
        "product", sa.Column("valid_code_start", mysql.DATETIME(), nullable=True)
    )
    op.add_column(
        "product", sa.Column("valid_code_end", mysql.DATETIME(), nullable=True)
    )
    op.create_table(
        "product_details",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("color", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("size", mysql.VARCHAR(length=256), nullable=True),
        sa.Column(
            "id_product",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status_stock",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_product"], ["product.id"], name="product_details_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_product_details_id", "product_details", ["id"], unique=False)
    # ### end Alembic commands ###
