"""update product

Revision ID: 9db6cc3d3345
Revises: 197039e4c21e
Create Date: 2023-11-11 17:13:55.450458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9db6cc3d3345"
down_revision = "197039e4c21e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("colors_disp", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "product", sa.Column("size_disp", sa.String(length=256), nullable=True)
    )
    op.add_column("user_product", sa.Column("id_product", sa.Integer(), nullable=True))
    op.drop_constraint("user_product_ibfk_2", "user_product", type_="foreignkey")
    op.create_foreign_key(None, "user_product", "product", ["id_product"], ["id"])
    op.drop_column("user_product", "id_product_details")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_product",
        sa.Column(
            "id_product_details",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "user_product", type_="foreignkey")
    op.create_foreign_key(
        "user_product_ibfk_2",
        "user_product",
        "product_details",
        ["id_product_details"],
        ["id"],
    )
    op.drop_column("user_product", "id_product")
    op.drop_column("product", "size_disp")
    op.drop_column("product", "colors_disp")
    # ### end Alembic commands ###
